task 6 complete
FergusJames212/Backend-News-Project pull request #6
Opened 2023-02-21 16:36 UTC by FergusJames212

2023-02-22 10:11 UTC, robert112233 requested changes
Great start 💯  Amend the tests and submit another PR for review!

2023-02-22 10:11 UTC, robert112233 commented on __tests__/app.test.js
> +      });
Missing test for sorting the comments 👍

2023-02-22 10:11 UTC, robert112233 commented on __tests__/app.test.js
> +});
This is a 200 not an error! If you want to render the comments on a facebook post you won't show an error, you will still just display the comments (0)

2023-02-22 10:11 UTC, robert112233 commented on __tests__/app.test.js
One missing test, if we request /api/articles/100000/comments it should give you back a 404. You made a checkExists / Promise.all to differentiate between valid articles with no comments: rows =[] and invalid articles: rows = [] 

This was covered in yesterday's lecture (I think, I wasn't there)

2023-02-23 09:47 UTC, Harrison365 commented
Nice work, Fergus 👍 
Merge away! ✅ 

Harrison :)

2023-02-23 09:57 UTC, merged